# Generated by Django 4.2 on 2024-04-07 16:16

import application.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО менеджера')),
                ('phone_number', models.CharField(help_text='Введите номер телефона в формате +7 977 900 00 00', max_length=20, validators=[application.utils.validate_phone], verbose_name='Номер телефона менеджера')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('На производстве', 'На производстве'), ('Упаковка', 'Упаковка'), ('Готов к отгрузке', 'Готов к отгрузке'), ('Готов', 'Готов')], default='Создан', max_length=50, verbose_name='Статус работы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('total_cost', models.FloatField(blank=True, null=True, verbose_name='Итоговая стоимость')),
                ('overdue', models.BooleanField(default=False, verbose_name='Просрочено или нет')),
                ('production_time', models.DateField(blank=True, null=True, verbose_name='Сроки изготовления')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manage_app', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('unit', models.CharField(choices=[('шт', 'шт'), ('кв', 'кв'), ('пог.м', 'пог.м')], max_length=10, verbose_name='Единица измерения')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(help_text='Введите номер телефона в формате +7 977 900 00 00', max_length=20, validators=[application.utils.validate_phone], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщик',
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100, verbose_name='Склад')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('in_stock', models.FloatField(verbose_name='Остаток')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='application.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Остатки',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт местонахождения объекта (город, поселок, станица и др.)')),
                ('street', models.CharField(max_length=100, verbose_name='Улица местонахождения объекта')),
                ('house', models.CharField(max_length=100, verbose_name='Дом местонахождения объекта')),
                ('dealer_name', models.CharField(max_length=100, verbose_name='Наименование дилера')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер от дилера (ФИО И номер телефона)')),
                ('main_name', models.CharField(max_length=100, verbose_name='ФИО, должность контактного лица с которым ведутся переговоры')),
                ('main_phone', models.CharField(max_length=100, verbose_name='Телефон контактного лица (Полностью без сокращений)')),
                ('full_address', models.CharField(max_length=255, verbose_name='Полный адрес')),
                ('full_name_object', models.CharField(max_length=100, verbose_name='Полное наименование объекта')),
                ('architect', models.CharField(max_length=100, verbose_name='Архитектор/ аритектурная организация')),
                ('investor', models.CharField(max_length=100, verbose_name='Инвестор/ застройщик')),
                ('materials', models.CharField(max_length=100, verbose_name='Конкурирующие материалы')),
                ('stages', models.CharField(max_length=100, verbose_name='Стадии реализации проекта')),
                ('date_of_delivery', models.DateField(verbose_name='Дата поставки')),
                ('document', models.FileField(blank=True, null=True, upload_to='document', verbose_name='Титульный лист/Или визуализация проекта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ApplicationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Образец')),
                ('warehouse', models.CharField(max_length=100, verbose_name='Склад')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product', verbose_name='Товар')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='products',
            field=models.ManyToManyField(related_name='applications', through='application.ApplicationProduct', to='application.product'),
        ),
        migrations.AddField(
            model_name='application',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.provider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
